/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StartModule;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Ali, Faqih, Muthi'ah
 */
public class AdminScreen extends javax.swing.JFrame {

    /**
     * Creates new form AdminScreen
     */
    public AdminScreen() {
        initComponents();
    }
    
    public AdminScreen(String nama []){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        createScreen = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        namaComp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fee = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        category = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressBox = new javax.swing.JTextArea();
        typeComp = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        descBox = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        prizePool = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        rules = new javax.swing.JTextArea();
        jToggleButton1 = new javax.swing.JToggleButton();
        contact = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setPreferredSize(new java.awt.Dimension(835, 580));

        jPanel1.setBackground(new java.awt.Color(247, 255, 171));

        createScreen.setBackground(new java.awt.Color(247, 255, 171));
        createScreen.setPreferredSize(new java.awt.Dimension(500, 500));
        createScreen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(208, 147, 215));
        jLabel2.setText("Create");
        createScreen.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        namaComp.setBackground(new java.awt.Color(249, 199, 255));
        createScreen.add(namaComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 770, -1));

        jLabel1.setText("Competition Name :");
        createScreen.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel3.setText("Competition Type :");
        createScreen.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 121, -1, -1));

        jLabel4.setText("Rules / Requirements :");
        createScreen.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 194, -1, -1));

        jLabel5.setText("Description :");
        createScreen.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 291, -1, -1));

        jLabel6.setText("Participation Fee:");
        createScreen.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 121, -1, -1));

        fee.setBackground(new java.awt.Color(249, 199, 255));
        fee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feeActionPerformed(evt);
            }
        });
        fee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                feeKeyTyped(evt);
            }
        });
        createScreen.add(fee, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 141, 134, -1));

        jLabel7.setText("Category:");
        createScreen.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 121, -1, -1));

        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose...", "Design", "Sports", "Poem", "DIY", "Music", "Literature", "Arts & Crafts", "Debate", "Coding", "Maths", "Other" }));
        category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryActionPerformed(evt);
            }
        });
        createScreen.add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 141, 140, -1));

        jLabel8.setText("Rp.");
        createScreen.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 144, -1, -1));

        jLabel10.setText("Address:");
        createScreen.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        addressBox.setBackground(new java.awt.Color(249, 199, 255));
        addressBox.setColumns(20);
        addressBox.setRows(5);
        addressBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(addressBox);

        createScreen.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 453, 770, 50));

        typeComp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose...", "'Academic", "Non-Academic", " " }));
        createScreen.add(typeComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 141, 113, -1));

        descBox.setBackground(new java.awt.Color(249, 199, 255));
        descBox.setColumns(20);
        descBox.setRows(5);
        descBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setViewportView(descBox);

        createScreen.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 311, 770, 50));

        jLabel9.setText("Prize Pool:");
        createScreen.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 121, -1, -1));

        prizePool.setBackground(new java.awt.Color(249, 199, 255));
        prizePool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prizePoolActionPerformed(evt);
            }
        });
        prizePool.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prizePoolKeyTyped(evt);
            }
        });
        createScreen.add(prizePool, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 141, 134, -1));

        jLabel11.setText("Rp.");
        createScreen.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 144, -1, -1));

        rules.setBackground(new java.awt.Color(249, 199, 255));
        rules.setColumns(20);
        rules.setRows(5);
        jScrollPane4.setViewportView(rules);

        createScreen.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 770, 70));

        jToggleButton1.setText("Create Listing");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        createScreen.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 509, -1, -1));

        contact.setBackground(new java.awt.Color(249, 199, 255));
        contact.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });
        createScreen.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 770, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StartModule/logoo.png"))); // NOI18N
        createScreen.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 520, 460));

        jLabel13.setText("Contact:");
        createScreen.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createScreen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//Untuk dipakai di frame lain    
public static String namaKos;
public static String alamatKos;


    //Masukan Data Dari Input User kepada Array
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        String ad = addressBox.getText();
        ad = (ad);
        UserHome.AddRowToJTable(new Object[] {
        namaComp.getText(), typeComp.getSelectedItem(), category.getSelectedItem(), fee.getText(), prizePool.getText(), rules.getText(),
            ad, descBox.getText()
        });
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void feeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_feeActionPerformed

    private void prizePoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prizePoolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prizePoolActionPerformed

    private void categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryActionPerformed

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactActionPerformed

    private void feeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_feeKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    
    }//GEN-LAST:event_feeKeyTyped

    private void prizePoolKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prizePoolKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        
    }
    }//GEN-LAST:event_prizePoolKeyTyped

    
    
    //Image path dan Resize Untuk Dipakai di Label



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminScreen().setVisible(true);
            }
        });
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addressBox;
    private javax.swing.JComboBox<String> category;
    private javax.swing.JTextField contact;
    private javax.swing.JPanel createScreen;
    private javax.swing.JTextArea descBox;
    private javax.swing.JTextField fee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField namaComp;
    private javax.swing.JTextField prizePool;
    private javax.swing.JTextArea rules;
    private javax.swing.JComboBox typeComp;
    // End of variables declaration//GEN-END:variables
}

